apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240307045107.0.0+build.6aff574
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240307045107.0.0+build.6aff574
  releaseNotes: |
    Release v20240307045107.0.0+build.6aff574 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-06-03-2024-18-07-11-919019966/where-for-dinner-search-my-apps-bundle@sha256:d35d42083991ac03de768f4882e84a19a238fa1fa3aa8c5615d8539745ae5b65
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

